version: "3.8"

services:
    nginx:
        build:
            context: .
            target: nginx
        depends_on:
            - php
            - node
        ports:
            - "9090:80"
        volumes:
            - ./.docker/nginx/conf.d/domain.conf:/etc/nginx/conf.d/default.conf:ro
        restart: unless-stopped

    php:
        build:
            context: .
            target: php
        depends_on:
            - node
        restart: unless-stopped

    node:
        build:
            context: .
            target: node
        environment:
            PHP_HOST: php
            PHP_PORT: 9000
        restart: unless-stopped
